fix default `_missing_` so a duplicate `ValueError` is not set as the `__context__` of the original `ValueError`
